### ISSUE TITLE
Problem with regex when enforcing labels

### ISSUE THREAD

**Issue by tonnihult** [forseti-security/policy-library#150]
Hi
I get a problem to run the config validator in Forseti after updating the enforce labels constraint GCPEnforceLabelConstraintV1 and it seems to have to do with the regex. When running with the default 
```terraform
    mandatory_labels: 
      - "label1": "^label1-value$"
      - "label2": "^label2-value.*$"
```
all works fine but when switching to
```terraform
    mandatory_labels: 
      - "environment": "^.*$"
      - "ownerteam": "^.*$"
```
we get the following error in GCP. 
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/forseti_security-2.19.0-py3.6.egg/google/cloud/forseti/scanner/scanners/config_validator_util/validator_client.py", line 106, in audit
    return self.stub.Audit(validator_pb2.AuditRequest()).violations
  File "/usr/local/lib/python3.6/dist-packages/grpc/_channel.py", line 550, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.6/dist-packages/grpc/_channel.py", line 467, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "templates.templates.gcpGCPEnforceLabelConstraintV1:70: eval_type_error: re_match: operand 2 must be string but got null"
	debug_error_string = "{"created":"@1565381035.178658072","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1036,"grpc_message":"templates.templates.gcpGCPEnforceLabelConstraintV1:70: eval_type_error: re_match: operand 2 must be string but got null","grpc_status":2}"
```

**Comment by AdrienWalkowiak** [comment]
Thanks for testing out this policy, I will look into this.

In the mean time, I think you could use:
```
   mandatory_labels: 
      - "environment": ".*"
      - "ownerteam": ".*"
```

to workaround the issue, until it's solved.

**Comment by AdrienWalkowiak** [comment]
I am not able to reproduce this, but it looks like it's an issue with the asset label value that is null somehow. It's possible that the checks I made to make sure it exists is failing in your case.

Could you add some debugging info here? It would be helpful to have the full CAI asset and the constraint you used to test it.

You can use the trace and sprintf command for this in the label_enforce.rego file on L66:

```
	trace(sprintf("asset: %s", [asset]))
	# test if label exists in asset
	resource_labels[label_key]

	# test if label value matches pattern passed as a parameter 
re_match(	label_value_pattern, resource_labels[label_key])
```

**Comment by ocervell** [comment]
Here is the error from Forseti VM:
```
"Error running scanner: ConfigValidatorScanner: 'Traceback (most recent call last):\n  File \"/usr/local/lib/python3
.6/dist-packages/forseti_security-2.19.1-py3.6.egg/google/cloud/forseti/scanner/scanners/config_validator_util/validator_client.py\", l
ine 106, in audit\n    return self.stub.Audit(validator_pb2.AuditRequest()).violations\n  File \"/usr/local/lib/python3.6/dist-packages
/grpc/_channel.py\", line 550, in __call__\n    return _end_unary_response_blocking(state, call, False, None)\n  File \"/usr/local/lib/
python3.6/dist-packages/grpc/_channel.py\", line 467, in _end_unary_response_blocking\n    raise _Rendezvous(state, None, None, deadlin
e)\ngrpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:\n\tstatus = StatusCode.UNKNOWN\n\tdetails = \"templates.templa
tes.gcpGCPEnforceLabelConstraintV1:73: eval_type_error: re_match: operand 2 must be string but got null\"\n\tdebug_error_string = \"{\"
created\":\"@1568386042.252988804\",\"description\":\"Error received from peer\",\"file\":\"src/core/lib/surface/call.cc\",\"file_line\
":1036,\"grpc_message\":\"templates.templates.gcpGCPEnforceLabelConstraintV1:73: eval_type_error: re_match: operand 2 must be string bu
t got null\",\"grpc_status\":2}\"\n>\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent c
all last):\n  File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.19.1-py3.6.egg/google/cloud/forseti/scanner/scanner.py\"
, line 119, in run\n    scanner.run()\n  File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.19.1-py3.6.egg/google/cloud/f
orseti/scanner/scanners/config_validator_scanner.py\", line 186, in run\n    all_violations = self._retrieve_flattened_violations()\n
File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.19.1-py3.6.egg/google/cloud/forseti/scanner/scanners/config_validator_
scanner.py\", line 167, in _retrieve_flattened_violations\n    violations = self.validator_client.audit()\n  File \"/home/ubuntu/forset
i-security/.eggs/retrying-1.3.3-py3.6.egg/retrying.py\", line 49, in wrapped_f\n    return Retrying(*dargs, **dkw).call(f, *args, **kw)
\n  File \"/home/ubuntu/forseti-security/.eggs/retrying-1.3.3-py3.6.egg/retrying.py\", line 206, in call\n    return attempt.get(self._
wrap_exception)\n  File \"/home/ubuntu/forseti-security/.eggs/retrying-1.3.3-py3.6.egg/retrying.py\", line 247, in get\n    six.reraise
(self.value[0], self.value[1], self.value[2])\n  File \"/usr/local/lib/python3.6/dist-packages/six.py\", line 693, in reraise\n    rais
e value\n  File \"/home/ubuntu/forseti-security/.eggs/retrying-1.3.3-py3.6.egg/retrying.py\", line 200, in call\n    attempt = Attempt(
fn(*args, **kwargs), attempt_number, False)\n  File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.19.1-py3.6.egg/google/c
loud/forseti/scanner/scanners/config_validator_util/validator_client.py\", line 113, in audit\n    LOGGER.exception('ConfigValidatorAud
itError: %s', e.message)\nAttributeError: '_Rendezvous' object has no attribute 'message'\n'"
```

**Comment by morgante** [comment]
@ocervell Does it work with CFT Scorecard?

**Comment by morgante** [comment]
@joecheuk Can you help out here on what would cause Forseti to fail for this constraint?

**Comment by AdrienWalkowiak** [comment]
This might be a Forseti version update. I ran my tests with Forseti v2.18.0 and the constraint worked as epxected. Are you using a different version?

**Comment by joecheuk** [comment]
Based on the log output, looks like version 2.19.1 is being deployed. The CV binary in the forseti application has not been updated since Jun 19. Looks like the error occurred in the audit() method in CV - is it possible that we might need to do additional null checks in the template to avoid edge cases like that? 

From Forseti PoV, we pass all the data to FCV so there might potentially be resources with empty labels is what I am guessing. 

There seems to be a check in place already: https://github.com/forseti-security/policy-library/blob/e83c9a874e57338f6917e205d67200fd3e722bf5/validator/enforce_labels.rego#L68
Not sure if that would catch all the cases.

**Comment by ocervell** [comment]
@joecheuk this doesn't happen when passing the same inventory / iam_policy dump to the config validator's `audit` function (using either `opa run ...` or CFT scorecard: since those are special types (regex), there must be something wrong when passing the data to `config-validator`. Was there changes to Forseti's config validator scanner since 2.18.0 ?

**Comment by jenshonkan84** [comment]
I am getting this error with latest forseti version 2.22.0

``` 
 "serverMessage": "Error running scanner: ConfigValidatorScanner: '\''Traceback (most recent call last):\n  File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.22.0-py3.6.egg/google/cloud/forseti/scanner/scanners/config_validator_util/validator_client.py\", line 107, in audit\n    return self.stub.Audit(validator_pb2.AuditRequest()).violations\n  File \"/usr/local/lib/python3.6/dist-packages/grpc/_channel.py\", line 550, in __call__\n    return _end_unary_response_blocking(state, call, False, None)\n  File \"/usr/local/lib/python3.6/dist-packages/grpc/_channel.py\", line 467, in _end_unary_response_blocking\n    raise _Rendezvous(state, None, None, deadline)\ngrpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:\n\tstatus = StatusCode.UNKNOWN\n\tdetails = \"templates.templates.gcpGCPEnforceLabelConstraintV1:71: eval_type_error: re_match: operand 2 must be string but got null\"\n\tdebug_error_string = \"{\"created\":\"@1570174357.417895598\",\"description\":\"Error received from peer\",\"file\":\"src/core/lib/surface/call.cc\",\"file_line\":1036,\"grpc_message\":\"templates.templates.gcpGCPEnforceLabelConstraintV1:71: eval_type_error: re_match: operand 2 must be string but got null\",\"grpc_status\":2}\"\n>\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.22.0-py3.6.egg/google/cloud/forseti/scanner/scanner.py\", line 119, in run\n    scanner.run()\n  File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.22.0-py3.6.egg/google/cloud/forseti/scanner/scanners/config_validator_scanner.py\", line 186, in run\n    all_violations = self._retrieve_flattened_violations()\n  File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.22.0-py3.6.egg/google/cloud/forseti/scanner/scanners/config_validator_scanner.py\", line 167, in _retrieve_flattened_violations\n    violations = self.validator_client.audit()\n  File \"/home/ubuntu/forseti-security/.eggs/retrying-1.3.3-py3.6.egg/retrying.py\", line 49, in wrapped_f\n    return Retrying(*dargs, **dkw).call(f, *args, **kw)\n  File \"/home/ubuntu/forseti-security/.eggs/retrying-1.3.3-py3.6.egg/retrying.py\", line 206, in call\n    return attempt.get(self._wrap_exception)\n  File \"/home/ubuntu/forseti-security/.eggs/retrying-1.3.3-py3.6.egg/retrying.py\", line 247, in get\n    six.reraise(self.value[0], self.value[1], self.value[2])\n  File \"/usr/local/lib/python3.6/dist-packages/six.py\", line 693, in reraise\n    raise value\n  File \"/home/ubuntu/forseti-security/.eggs/retrying-1.3.3-py3.6.egg/retrying.py\", line 200, in call\n    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)\n  File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.22.0-py3.6.egg/google/cloud/forseti/scanner/scanners/config_validator_util/validator_client.py\", line 114, in audit\n    LOGGER.exception('\''ConfigValidatorAuditError: %s'\'', e.message)\nAttributeError: '\''_Rendezvous'\'' object has no attribute '\''message'\''\n'\''"

```

**Comment by AdrienWalkowiak** [comment]
After some testing, it seems that the rule works well with some parameters but not all. I am trying to narrow down which ones are fine and which ones do not work in Forseti at this point.

Could you guys (@ocervell, @tonnihult  and @jenshonkan84 ) specify which parameters you are testing?

**Comment by jenshonkan84** [comment]
Here is my constraints file:

```
apiVersion: constraints.gatekeeper.sh/v1alpha1
kind: GCPEnforceLabelConstraintV1
metadata:
  name: require_labels
spec:
  severity: low
  match:
    target: ["organization/*"]
  parameters:
    mandatory_labels:
      # - "label1": "^label1-value$"
      # - "label2": "^label2-value.*$"
      - "costcenter": ".*"
      - "ownerteam": ".*"
```

**Comment by gkowalski-google** [comment]
@jenshonkan84 Following up to see if you are able to confirm if you still see this issue after upgrading to the latest version of Forseti?
